### ISSUE TITLE
Deplyment on web server

### ISSUE THREAD

**Issue by jackpoll** [oermolaev/simple-scala-rest-example#1]
I liked very much your closed completed working example. and used it as guide to building my web application. but when I've tried to deploy it into production, I came to a dead end.

How can I deploy this app to an external server? I want to deploy it into tomcat and tried to use xsbt-web-plugin but always geting a 404 from Tomcat although it runs fine when using the spray-can embedded server.

I've saw this question in the blog as well, seems there are more peoples struggling with that.

Do you know how can I do that?

Thanks.

**Comment by oermolaev** [comment]
Hi, 

I've modified the example to make it possible to deploy it into tomcat. Please, take a look on the code in the 'spray-tomcat' branch. You can find more details in my comment to the article on SysGears website: http://sysgears.com/articles/building-rest-service-with-scala/#comment-1989882292.

Thanks for a good question!

**Comment by jackpoll** [comment]
Works great!

Thank you very much for the full support.
